package com.angus.topdemo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.angus.topdemo.entities.Topclass;
import com.angus.topdemo.entities.Top;

import com.angus.topdemo.dao.TopclassDao;
import com.angus.topdemo.dao.TopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topclassDaoConfig;
    private final DaoConfig topDaoConfig;

    private final TopclassDao topclassDao;
    private final TopDao topDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topclassDaoConfig = daoConfigMap.get(TopclassDao.class).clone();
        topclassDaoConfig.initIdentityScope(type);

        topDaoConfig = daoConfigMap.get(TopDao.class).clone();
        topDaoConfig.initIdentityScope(type);

        topclassDao = new TopclassDao(topclassDaoConfig, this);
        topDao = new TopDao(topDaoConfig, this);

        registerDao(Topclass.class, topclassDao);
        registerDao(Top.class, topDao);
    }
    
    public void clear() {
        topclassDaoConfig.getIdentityScope().clear();
        topDaoConfig.getIdentityScope().clear();
    }

    public TopclassDao getTopclassDao() {
        return topclassDao;
    }

    public TopDao getTopDao() {
        return topDao;
    }

}
