package com.angus.topdemo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.angus.topdemo.entities.Top;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TOP".
*/
public class TopDao extends AbstractDao<Top, Long> {

    public static final String TABLENAME = "TOP";

    /**
     * Properties of entity Top.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Img = new Property(2, String.class, "img", false, "IMG");
        public final static Property Description = new Property(3, String.class, "description", false, "DESCRIPTION");
        public final static Property Keywords = new Property(4, String.class, "keywords", false, "KEYWORDS");
        public final static Property Message = new Property(5, String.class, "message", false, "MESSAGE");
        public final static Property Fromname = new Property(6, String.class, "fromname", false, "FROMNAME");
        public final static Property Fromurl = new Property(7, String.class, "fromurl", false, "FROMURL");
        public final static Property Topclass = new Property(8, Long.class, "topclass", false, "TOPCLASS");
        public final static Property Count = new Property(9, Integer.class, "count", false, "COUNT");
        public final static Property Fcount = new Property(10, Integer.class, "fcount", false, "FCOUNT");
        public final static Property Rcount = new Property(11, Integer.class, "rcount", false, "RCOUNT");
        public final static Property Time = new Property(12, java.util.Date.class, "time", false, "TIME");
    };


    public TopDao(DaoConfig config) {
        super(config);
    }
    
    public TopDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TOP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"IMG\" TEXT," + // 2: img
                "\"DESCRIPTION\" TEXT," + // 3: description
                "\"KEYWORDS\" TEXT," + // 4: keywords
                "\"MESSAGE\" TEXT," + // 5: message
                "\"FROMNAME\" TEXT," + // 6: fromname
                "\"FROMURL\" TEXT," + // 7: fromurl
                "\"TOPCLASS\" INTEGER," + // 8: topclass
                "\"COUNT\" INTEGER," + // 9: count
                "\"FCOUNT\" INTEGER," + // 10: fcount
                "\"RCOUNT\" INTEGER," + // 11: rcount
                "\"TIME\" INTEGER);"); // 12: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TOP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Top entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(3, img);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
 
        String keywords = entity.getKeywords();
        if (keywords != null) {
            stmt.bindString(5, keywords);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(6, message);
        }
 
        String fromname = entity.getFromname();
        if (fromname != null) {
            stmt.bindString(7, fromname);
        }
 
        String fromurl = entity.getFromurl();
        if (fromurl != null) {
            stmt.bindString(8, fromurl);
        }
 
        Long topclass = entity.getTopclass();
        if (topclass != null) {
            stmt.bindLong(9, topclass);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(10, count);
        }
 
        Integer fcount = entity.getFcount();
        if (fcount != null) {
            stmt.bindLong(11, fcount);
        }
 
        Integer rcount = entity.getRcount();
        if (rcount != null) {
            stmt.bindLong(12, rcount);
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(13, time.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Top readEntity(Cursor cursor, int offset) {
        Top entity = new Top( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // img
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // keywords
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // message
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fromname
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // fromurl
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // topclass
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // count
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // fcount
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // rcount
            cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Top entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setKeywords(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMessage(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFromname(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFromurl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTopclass(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setCount(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setFcount(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setRcount(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setTime(cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Top entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Top entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
